In [4]:
import pandas as pd
import numpy as np

In [80]:
data = pd.read_csv('iris-data.csv', header=None)

In [81]:
data.columns = ['sepal length', 'sepal width', 'petal length', 'petal width', 'class']

In [82]:
data['bias'] = 1

In [83]:
data['class'][data['class'] == 'Iris-setosa'] = 1
data['class'][data['class'] == 'Iris-versicolor'] = 2
data['class'][data['class'] == 'Iris-virginica'] = 3

/home/tushar/anaconda3/envs/pycharm/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/tushar/anaconda3/envs/pycharm/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/home/tushar/anaconda3/envs/pycharm/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel 

In [84]:
data[50:75]

sepal length  sepal width  petal length  petal width class  bias
50           7.0          3.2           4.7          1.4     2     1
51           6.4          3.2           4.5          1.5     2     1
52           6.9          3.1           4.9          1.5     2     1
53           5.5          2.3           4.0          1.3     2     1
54           6.5          2.8           4.6          1.5     2     1
55           5.7          2.8           4.5          1.3     2     1
56           6.3          3.3           4.7          1.6     2     1
57           4.9          2.4           3.3          1.0     2     1
58           6.6          2.9           4.6          1.3     2     1
59           5.2          2.7           3.9          1.4     2     1
60           5.0          2.0           3.5          1.0     2     1
61           5.9          3.0           4.2          1.5     2     1
62           6.0          2.2           4.0          1.0     2     1
63           6.1          2.9           4.7          1.4     2     1
64           5.6          2.9           3.6          1.3     2     1
65           6.7          3.1           4.4          1.4     2     1
66           5.6          3.0           4.5          1.5     2     1
67           5.8          2.7           4.1          1.0     2     1
68           6.2          2.2           4.5          1.5     2     1
69           5.6          2.5           3.9          1.1     2     1
70           5.9          3.2           4.8          1.8     2     1
71           6.1          2.8           4.0          1.3     2     1
72           6.3          2.5           4.9          1.5     2     1
73           6.1          2.8           4.7          1.2     2     1
74           6.4          2.9           4.3          1.3     2     1

In [85]:
df1 = data[0:25]
df1 = df1.append(data[50:75])
df1 = df1.append(data[100:125])

In [86]:
df2 = data[25:50]
df2 = df2.append(data[75:100])
df2 = df2.append(data[125:150])

In [87]:
df1_mat = df1.as_matrix(columns=['sepal length','sepal width','petal length','petal width','bias'])

/home/tushar/anaconda3/envs/pycharm/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [88]:
df1_mat.shape

(75, 5)

In [89]:
sum1 = 0
for val in df1_mat:
    val1 = np.reshape(val, (1, len(val)))
    sum1 += (val1.T * val1)

In [90]:
sum1.shape

(5, 5)

In [91]:
df1_class = (df1['class'] - 1).apply(lambda x : np.eye(3)[x])

In [92]:
df1_class = np.array(df1_class)

In [93]:
sum2 = 0
for i in range(len(df1_mat)):
    val1 = np.reshape(df1_mat[i], (len(df1_mat[i]), 1))
    sum2 += (val1 * df1_class[i].reshape(1,3))

In [94]:
sum2

array([[125.7, 150.3, 164.4],
       [ 87. ,  69.4,  73.2],
       [ 36.5, 107.8, 141. ],
       [  6.2,  33.6,  51.1],
       [ 25. ,  25. ,  25. ]])

In [95]:
lda = 0.0001

In [96]:
sum1 = sum1 + lda

In [97]:
w = np.matmul(sum1.T, sum2) 

In [98]:
w

array([[528176.38204, 711656.40461, 822916.85247],
       [269752.34404, 357660.54761, 412045.03047],
       [354837.11504, 490600.16461, 570743.39847],
       [114716.71804, 160068.69361, 186640.21247],
       [ 88185.53804, 117810.97861, 135955.81547]])

In [65]:
w[:,0]

array([528176.38204, 269752.34404, 354837.11504, 114716.71804,
        88185.53804])

In [59]:
df2_mat = df2.as_matrix(columns=['sepal length','sepal width','petal length','petal width','bias'])

/home/tushar/anaconda3/envs/pycharm/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [71]:
fin_cla_w = [[],[],[]]
for i in range(len(fin_cla_w)):
    for val in df2_mat:
        val1 = np.reshape(val, (1, len(val)))
        weights = np.matmul(val1, w[:, i])[0]
        fin_cla_w[i].append(weights)

In [72]:
np.array(fin_cla_w).shape

(3, 75)

In [78]:
final_classes = []
for val in np.array(fin_cla_w).T:
    final_classes.append(np.argmax(val))

In [79]:
final_classes

[2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

In [75]:
final_df = pd.DataFrame(np.array(fin_cla_w).T)

In [76]:
final_arr

0             1             2
0   4.129007e+06  5.566049e+06  6.437193e+06
1   4.259851e+06  5.741127e+06  6.639339e+06
2   4.334035e+06  5.838150e+06  6.750724e+06
3   4.271576e+06  5.753324e+06  6.652445e+06
4   4.024505e+06  5.424084e+06  6.272727e+06
5   4.050347e+06  5.459483e+06  6.313814e+06
6   4.435638e+06  5.976729e+06  6.911431e+06
7   4.484415e+06  6.036740e+06  6.979287e+06
8   4.645831e+06  6.252949e+06  7.228956e+06
9   4.056209e+06  5.465582e+06  6.320367e+06
10  4.041023e+06  5.441341e+06  6.291304e+06
11  4.421520e+06  5.953527e+06  6.883451e+06
12  4.056209e+06  5.465582e+06  6.320367e+06
13  3.705650e+06  4.991875e+06  5.772220e+06
14  4.254242e+06  5.731218e+06  6.627228e+06
15  4.168904e+06  5.613706e+06  6.490656e+06
16  3.581113e+06  4.828685e+06  5.584744e+06
17  3.759601e+06  5.063407e+06  5.854629e+06
18  4.309770e+06  5.808906e+06  6.717871e+06
19  4.527021e+06  6.102537e+06  7.057671e+06
20  3.963876e+06  5.341604e+06  6.177125e+06
21  4.397627e+06  5.923343e+06  6.849120e+06
22  3.900720e+06  5.254798e+06  6.076286e+06
23  4.440803e+06  5.980848e+06  6.915425e+06
24  4.138965e+06  5.575227e+06  6.446657e+06
25  6.105293e+06  8.270462e+06  9.575909e+06
26  6.298913e+06  8.537501e+06  9.886381e+06
27  6.405428e+06  8.684008e+06  1.005664e+07
28  5.808368e+06  7.872769e+06  9.116693e+06
29  5.156794e+06  6.981339e+06  8.082141e+06
..           ...           ...           ...
45  5.536024e+06  7.499837e+06  8.683807e+06
46  5.520520e+06  7.480078e+06  8.661267e+06
47  5.820092e+06  7.884966e+06  9.129800e+06
48  4.646966e+06  6.289286e+06  7.280479e+06
49  5.458061e+06  7.395252e+06  8.562988e+06
50  7.089776e+06  9.617975e+06  1.113991e+07
51  6.027894e+06  8.174535e+06  9.467287e+06
52  6.064510e+06  8.223961e+06  9.524479e+06
53  6.451814e+06  8.757367e+06  1.014446e+07
54  6.941915e+06  9.416310e+06  1.090603e+07
55  7.134465e+06  9.682309e+06  1.121542e+07
56  7.786229e+06  1.055899e+07  1.222881e+07
57  6.463286e+06  8.773374e+06  1.016312e+07
58  6.152748e+06  8.344860e+06  9.664810e+06
59  6.159109e+06  8.360290e+06  9.684525e+06
60  7.392756e+06  1.003137e+07  1.161936e+07
61  6.595263e+06  8.948818e+06  1.036538e+07
62  6.462841e+06  8.767584e+06  1.015500e+07
63  5.976209e+06  8.103735e+06  9.385113e+06
64  6.725860e+06  9.122373e+06  1.056538e+07
65  6.725608e+06  9.126182e+06  1.057094e+07
66  6.642353e+06  9.007207e+06  1.043149e+07
67  5.907571e+06  8.017293e+06  9.286803e+06
68  6.900380e+06  9.364287e+06  1.084699e+07
69  6.826513e+06  9.262781e+06  1.072909e+07
70  6.545226e+06  8.878169e+06  1.028277e+07
71  6.082225e+06  8.252529e+06  9.558778e+06
72  6.405175e+06  8.687817e+06  1.006220e+07
73  6.460006e+06  8.763525e+06  1.015028e+07
74  6.029843e+06  8.179750e+06  9.474044e+06

[75 rows x 3 columns]

In [77]:
data.sample(frac=1)

sepal length  sepal width  petal length  petal width class  bias
92            5.8          2.6           4.0          1.2     2     1
33            5.5          4.2           1.4          0.2     1     1
1             4.9          3.0           1.4          0.2     1     1
76            6.8          2.8           4.8          1.4     2     1
94            5.6          2.7           4.2          1.3     2     1
128           6.4          2.8           5.6          2.1     3     1
70            5.9          3.2           4.8          1.8     2     1
72            6.3          2.5           4.9          1.5     2     1
32            5.2          4.1           1.5          0.1     1     1
139           6.9          3.1           5.4          2.1     3     1
38            4.4          3.0           1.3          0.2     1     1
7             5.0          3.4           1.5          0.2     1     1
27            5.2          3.5           1.5          0.2     1     1
146           6.3          2.5           5.0          1.9     3     1
60            5.0          2.0           3.5          1.0     2     1
62            6.0          2.2           4.0          1.0     2     1
109           7.2          3.6           6.1          2.5     3     1
131           7.9          3.8           6.4          2.0     3     1
19            5.1          3.8           1.5          0.3     1     1
81            5.5          2.4           3.7          1.0     2     1
30            4.8          3.1           1.6          0.2     1     1
99            5.7          2.8           4.1          1.3     2     1
46            5.1          3.8           1.6          0.2     1     1
11            4.8          3.4           1.6          0.2     1     1
17            5.1          3.5           1.4          0.3     1     1
138           6.0          3.0           4.8          1.8     3     1
125           7.2          3.2           6.0          1.8     3     1
36            5.5          3.5           1.3          0.2     1     1
144           6.7          3.3           5.7          2.5     3     1
43            5.0          3.5           1.6          0.6     1     1
..            ...          ...           ...          ...   ...   ...
130           7.4          2.8           6.1          1.9     3     1
142           5.8          2.7           5.1          1.9     3     1
4             5.0          3.6           1.4          0.2     1     1
78            6.0          2.9           4.5          1.5     2     1
41            4.5          2.3           1.3          0.3     1     1
47            4.6          3.2           1.4          0.2     1     1
117           7.7          3.8           6.7          2.2     3     1
143           6.8          3.2           5.9          2.3     3     1
82            5.8          2.7           3.9          1.2     2     1
106           4.9          2.5           4.5          1.7     3     1
141           6.9          3.1           5.1          2.3     3     1
39            5.1          3.4           1.5          0.2     1     1
77            6.7          3.0           5.0          1.7     2     1
132           6.4          2.8           5.6          2.2     3     1
40            5.0          3.5           1.3          0.3     1     1
73            6.1          2.8           4.7          1.2     2     1
126           6.2          2.8           4.8          1.8     3     1
120           6.9          3.2           5.7          2.3     3     1
50            7.0          3.2           4.7          1.4     2     1
63            6.1          2.9           4.7          1.4     2     1
24            4.8          3.4           1.9          0.2     1     1
103           6.3          2.9           5.6          1.8     3     1
112           6.8          3.0           5.5          2.1     3     1
31            5.4          3.4           1.5          0.4     1     1
101           5.8          2.7           5.1          1.9     3     1
3             4