In [4]:
import pandas as pd
import numpy as np

In [142]:
data = pd.read_csv('iris-data.csv', header=None)

In [143]:
data.columns = ['sepal length', 'sepal width', 'petal length', 'petal width', 'class']

In [144]:
data['bias'] = 1

In [145]:
data['class'][data['class'] == 'Iris-setosa'] = 1
data['class'][data['class'] == 'Iris-versicolor'] = 2
data['class'][data['class'] == 'Iris-virginica'] = 3

/home/tushar/anaconda3/envs/pycharm/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/tushar/anaconda3/envs/pycharm/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/home/tushar/anaconda3/envs/pycharm/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel 

In [146]:
data[50:75]

sepal length  sepal width  petal length  petal width class  bias
50           7.0          3.2           4.7          1.4     2     1
51           6.4          3.2           4.5          1.5     2     1
52           6.9          3.1           4.9          1.5     2     1
53           5.5          2.3           4.0          1.3     2     1
54           6.5          2.8           4.6          1.5     2     1
55           5.7          2.8           4.5          1.3     2     1
56           6.3          3.3           4.7          1.6     2     1
57           4.9          2.4           3.3          1.0     2     1
58           6.6          2.9           4.6          1.3     2     1
59           5.2          2.7           3.9          1.4     2     1
60           5.0          2.0           3.5          1.0     2     1
61           5.9          3.0           4.2          1.5     2     1
62           6.0          2.2           4.0          1.0     2     1
63           6.1          2.9           4.7          1.4     2     1
64           5.6          2.9           3.6          1.3     2     1
65           6.7          3.1           4.4          1.4     2     1
66           5.6          3.0           4.5          1.5     2     1
67           5.8          2.7           4.1          1.0     2     1
68           6.2          2.2           4.5          1.5     2     1
69           5.6          2.5           3.9          1.1     2     1
70           5.9          3.2           4.8          1.8     2     1
71           6.1          2.8           4.0          1.3     2     1
72           6.3          2.5           4.9          1.5     2     1
73           6.1          2.8           4.7          1.2     2     1
74           6.4          2.9           4.3          1.3     2     1

In [147]:
data_c0 = data[data["class"]==1]
data_c1 = data[data["class"]==2]
data_c2 = data[data["class"]==3]
data_c0_train = data_c0[0:int(.12*(data_c0.shape[0]))]
data_c1_train = data_c1[0:int(.12*(data_c1.shape[0]))]
data_c2_train = data_c2[0:int(.12*(data_c2.shape[0]))]
data_train = pd.concat([data_c0_train,data_c1_train,data_c2_train])
data_test_index = [idx for idx in list(data.index) if idx not in list(data_train.index)]
data_test = data.loc[data_test_index]

In [148]:
df1 = data_train

In [149]:
df2 = data_test

In [150]:
df1_mat = df1.as_matrix(columns=['sepal length','sepal width','petal length','petal width','bias'])

/home/tushar/anaconda3/envs/pycharm/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [151]:
df1_mat.shape

(18, 5)

In [152]:
sum1 = 0
for val in df1_mat:
    val1 = np.reshape(val, (1, len(val)))
    sum1 += (val1.T * val1)

In [153]:
sum1.shape

(5, 5)

In [154]:
df1_class = (df1['class'] - 1).apply(lambda x : np.eye(3)[x])

In [155]:
df1_class = np.array(df1_class)

In [156]:
sum2 = 0
for i in range(len(df1_mat)):
    val1 = np.reshape(df1_mat[i], (len(df1_mat[i]), 1))
    sum2 += (val1 * df1_class[i].reshape(1,3))

In [157]:
sum2

array([[29.7, 38. , 39.6],
       [20.3, 17.4, 17.9],
       [ 8.7, 27.2, 35. ],
       [ 1.4,  8.5, 12.6],
       [ 6. ,  6. ,  6. ]])

In [158]:
lda = 0.0001

In [159]:
sum1 = sum1 + lda

In [160]:
w = np.matmul(np.linalg.inv(sum1), sum2) 

In [161]:
w

array([[-0.08861505,  0.4940819 , -0.40543559],
       [ 0.34081517, -0.78265794,  0.44197839],
       [-0.15215294, -0.09632163,  0.24858067],
       [-0.04888267, -0.28950421,  0.33813838],
       [ 0.46925123,  0.54688082, -0.01685022]])

In [162]:
w[:,0]

array([-0.08861505,  0.34081517, -0.15215294, -0.04888267,  0.46925123])

In [163]:
df2_mat = df2.as_matrix(columns=['sepal length','sepal width','petal length','petal width','bias'])

/home/tushar/anaconda3/envs/pycharm/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [164]:
fin_cla_w = [[],[],[]]
for i in range(len(fin_cla_w)):
    for val in df2_mat:
        val1 = np.reshape(val, (1, len(val)))
        weights = np.matmul(val1, w[:, i])[0]
        fin_cla_w[i].append(weights)

In [165]:
np.array(fin_cla_w).shape

(3, 132)

In [166]:
final_classes = []
for val in np.array(fin_cla_w).T:
    final_classes.append(np.argmax(val))

In [173]:
len(final_classes)

132

In [176]:
arr = np.zeros(len(final_classes))

In [177]:
arr[int(0.33*len(final_classes)):int(0.66*len(final_classes))] = 1
arr[int(0.66*len(final_classes)):int(1.0*len(final_classes))] = 2

In [178]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [179]:
 from sklearn.metrics import confusion_matrix

In [180]:
confusion_matrix(np.array(final_classes), arr)

array([[42,  2,  0],
       [ 1, 28, 13],
       [ 0, 14, 32]])

In [181]:
from sklearn.metrics import accuracy_score
1-accuracy_score(np.array(final_classes), arr)

0.2272727272727273